AWSTemplateFormatVersion: 2010-09-09
Description: Point domain name to CloudFront distribution

Parameters:
  DomainName:
    Type: String
    Description: Domain name
    Default: aprovan.com
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID
    Default: Z046909917DGKP7W30GBS
  DistributionDomainName:
    Type: String
    Description: Name of CloudFront distribution

Resources:
  Route53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: !Sub "Point ${DomainName} to ${DistributionDomainName}"
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub "${DomainName}."
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !Sub "${DistributionDomainName}."
  WwwRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: !Sub "Point www.${DomainName} to ${DistributionDomainName}"
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub "www.${DomainName}."
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !Sub "${DistributionDomainName}."
